### ISSUE TITLE
Archivio ZIP scaricato dal sito non valido

### ISSUE THREAD

**Issue by iz8mbw** [virtualdj/pun_sensor#30]
Ciao.
Nel log di Home Assistant ho l'errore:

```2023-12-06 01:00:51.759 WARNING (MainThread) [custom_components.pun_sensor] Errore durante l'aggiornamento via web, nuovo tentativo tra 1 minuto.
Traceback (most recent call last):
  File "/config/custom_components/pun_sensor/__init__.py", line 194, in _async_update_data
    archive = zipfile.ZipFile(io.BytesIO(await response.read()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.11/zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/pun_sensor/__init__.py", line 292, in update_pun
    await self._async_update_data()
  File "/config/custom_components/pun_sensor/__init__.py", line 197, in _async_update_data
    raise UpdateFailed('Archivio ZIP scaricato dal sito non valido.')
homeassistant.helpers.update_coordinator.UpdateFailed: Archivio ZIP scaricato dal sito non valido.
2023-12-06 01:01:53.576 WARNING (MainThread) [custom_components.pun_sensor] Errore durante l'aggiornamento via web, nuovo tentativo tra 10 minuti.
Traceback (most recent call last):
  File "/config/custom_components/pun_sensor/__init__.py", line 194, in _async_update_data
    archive = zipfile.ZipFile(io.BytesIO(await response.read()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.11/zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/pun_sensor/__init__.py", line 292, in update_pun
    await self._async_update_data()
  File "/config/custom_components/pun_sensor/__init__.py", line 197, in _async_update_data
    raise UpdateFailed('Archivio ZIP scaricato dal sito non valido.')
homeassistant.helpers.update_coordinator.UpdateFailed: Archivio ZIP scaricato dal sito non valido.
```

**Comment by virtualdj** [comment]
Ciao, potrebbe essere stato un errore temporaneo del sito. In sostanza il log dice che quanto scaricato dal sito (il file ZIP con i dati del mese) non è un vero file ZIP... probabilmente ha scaricato "fuffa" (o 0 bytes).

Però poi dovrebbe aver riprovato, infatti c'è il messaggio:

`2023-12-06 01:01:53.576 WARNING (MainThread) [custom_components.pun_sensor] Errore durante l'aggiornamento via web, nuovo tentativo tra 10 minuti.`

Dopo i 10 minuti ha funzionato? Immagino di sì, in tal caso puoi semplicemente ignorare l'errore.
