### ISSUE TITLE
Errore durante l'aggiornamento via web

### ISSUE THREAD

**Issue by Destroyer061090** [virtualdj/pun_sensor#35]
Ciao, 
ho trovato nei log questo warning che si ripete piu volte. possibile correggerlo?

Errore durante l'aggiornamento via web, nuovo tentativo tra 10 minuti.
Traceback (most recent call last):
  File "/config/custom_components/pun_sensor/__init__.py", line 308, in update_pun
    await self._async_update_data()
  File "/config/custom_components/pun_sensor/__init__.py", line 185, in _async_update_data
    viewstate = soup.find('input',{'name':'__VIEWSTATE'})['value']
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by virtualdj** [comment]
Mmm ce ne ho uno anch'io ma diverso:
```text
2024-02-13 20:34:03.163 DEBUG (MainThread) [custom_components.pun_sensor] Coordinator inizializzato (con 'usa dati reali' = False).
2024-02-13 20:34:03.165 DEBUG (MainThread) [custom_components.pun_sensor] Ora corrente sistema: Tue 13/02/2024 20:34:03 +0100
2024-02-13 20:34:03.165 DEBUG (MainThread) [custom_components.pun_sensor] Ora corrente fuso orario italiano: Tue 13/02/2024 20:34:03 +0100
2024-02-13 20:34:03.501 INFO (MainThread) [custom_components.pun_sensor] Nuova fascia corrente: F2 (prossima: Tue 13/02/2024 23:00:00 +0100)
2024-02-13 20:34:03.501 DEBUG (MainThread) [custom_components.pun_sensor] Manually updated pun_sensor data
2024-02-13 20:34:13.985 DEBUG (MainThread) [custom_components.pun_sensor] Connessione a URL login.
2024-02-13 20:34:14.384 DEBUG (MainThread) [custom_components.pun_sensor] Invio credenziali a URL login.
2024-02-13 20:36:19.791 WARNING (MainThread) [custom_components.pun_sensor] Errore durante l'aggiornamento via web, nuovo tentativo tra 1 minuto.
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/client_proto.py", line 83, in connection_lost
uncompleted = self._parser.feed_eof()
^^^^^^^^^^^^^^^^^^^^^^^
File "aiohttp/_http_parser.pyx", line 510, in aiohttp._http_parser.HttpParser.feed_eof
aiohttp.http_exceptions.ContentLengthError: 400, message:
Not enough data for satisfy content length header.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/pun_sensor/__init__.py", line 308, in update_pun
await self._async_update_data()
File "/config/custom_components/pun_sensor/__init__.py", line 182, in _async_update_data
soup = BeautifulSoup(await response.read(), features='html.parser')
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1101, in read
self._body = await self.content.read()
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 373, in read
block = await self.readany()
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 395, in readany
await self._wait("readany")
File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 302, in _wait
await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
```
poi però al tentativo successivo ha funzionato.
Riesci a mandarmi il log completo così provo a scavare più a fondo (non appena possibile)?

**Comment by virtualdj** [comment]
Sembra anche questo un problema di connessione (cioè del sito), comunque, perché riavviando HA non sempre appare.

**Comment by virtualdj** [comment]
@Destroyer061090 È più capitato?

**Comment by Destroyer061090** [comment]
> @Destroyer061090 È più capitato?

Ad oggi no…

**Comment by virtualdj** [comment]
@Destroyer061090 Bene, confermato quindi che era un problema temporaneo (del sito).

Io comunque non eliminerei l'errore dal log perché almeno così dall'eccezione si capisce cosa lo causa. Dopotutto c'è già il sistema che riprova in automatico, quindi credo che "sporcare i log" sia corretto in caso di problemi.
