### ISSUE TITLE
Componente non riceve dati

### ISSUE THREAD

**Issue by sagitt** [virtualdj/pun_sensor#66]
Ciao,
non so se è già conoscuto il problema ma noto che il mio sensore pun non si aggiorna più.

```
Registratore: custom_components.pun_sensor
Fonte: custom_components/pun_sensor/__init__.py:335
Integrazione: Prezzi PUN del mese ([documentazione](https://github.com/virtualdj/pun_sensor), [problemi](https://github.com/virtualdj/pun_sensor/issues))
Prima occorrenza: 01:05:13 (4 occorrenze)
Ultima registrazione: 01:17:20

Errore durante l'aggiornamento via web, nuovo tentativo tra 1 minuto.
Errore durante l'aggiornamento via web, nuovo tentativo tra 10 minuti.
Errore durante l'aggiornamento via web, nuovo tentativo tra 60 minuti.
Traceback (most recent call last):
  File "/config/custom_components/pun_sensor/__init__.py", line 216, in _async_update_data
    archive = zipfile.ZipFile(io.BytesIO(await response.read()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1349, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1416, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/pun_sensor/__init__.py", line 335, in update_pun
    await self._async_update_data()
  File "/config/custom_components/pun_sensor/__init__.py", line 219, in _async_update_data
    raise UpdateFailed('Archivio ZIP scaricato dal sito non valido.')
homeassistant.helpers.update_coordinator.UpdateFailed: Archivio ZIP scaricato dal sito non valido.
```

**Comment by Dany1800** [comment]
Da quando si è aggiornato il sistema ho lo stesso problema 😞

**Comment by Krasto82** [comment]
Idem anche io, si vede solo la fascia corrente ma i prezzi non sono più disponibili.

**Comment by virtualdj** [comment]
Ciao, dovete aggiornare all'ultima versione 0.9.4, perché da ottobre è cambiato l'URL da dove i dati vengono scaricati. 

Se cercate nelle issue chiuse c'è anche la procedura nel caso non funzionasse.

**Comment by Dany1800** [comment]
Grazie mille, non so ma per qualche motivo l'aggiornamento automatico era
disattivato.

Il lun 7 ott 2024, 13:15 Sagitt ***@***.***> ha scritto:

**Comment by Krasto82** [comment]
Grazie, infatti ero fermo alla 0.9.3 e non mi notificava l'aggiornamento in HACS (HACS è aggiornato alla nuova versione 2.1 con notifica update)
